services:
  watchdigest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watchdigest
    image: watchdigest:latest
    ports:
      - 5151:5151
    volumes:
      - ./config.json:/watchdigest/config.json
      - ./data.db:/watchdigest/data.db
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt:/opt
    environment:
      - TZ=UTC
    restart: always

