version: "3.8"
services:
  watchdigest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watchdigest
    image: watchdigest:latest
    volumes:
      - ./config.json:/watchdigest/config.json
      - ./data.db:/watchdigest/data.db
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Etc/UTC
    restart: always

